#! /usr/bin/env python3

'''
The main entry for all tasks.
'''

import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Main entry for multiple functions.")

    subparsers = parser.add_subparsers(dest="command", required=True)

    from src.tasks import task_train
    task_train.build_parser(subparsers)
    # ./main train --ckpt=ckpt/lunarlanding/v5 --init --arch=rmsmlp --hidden_layers=5 --grad_norm_clip=10.0 --steps=3500 --device=cpu

    from src.tasks import task_train_bm
    task_train_bm.build_parser(subparsers)
    # ./main train_bm --device=mps

    from src.tasks import task_landingM
    task_landingM.build_parser(subparsers)
    # ./main landingM --arch=rmsmlp --ckpt=ckpt/lunarlanding/v10/model_final.pth --hidden_layers=3

    from src.tasks import task_landingH
    task_landingH.build_parser(subparsers)
    # ./main landingH


    # Parse arguments
    args = parser.parse_args()
    
    # Call the function associated with the chosen command
    args.func(args)