#! /usr/bin/env python3

'''
The main entry for all tasks.
'''

import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Main entry for multiple functions.")

    subparsers = parser.add_subparsers(dest="command", required=True)

    from src.tasks import task_show_env
    task_show_env.build_parser(subparsers)
    # ./main show_env LunarLander-v3

    from src.tasks import task_train
    task_train.build_parser(subparsers)
    # ./main train LunarLander-v3 a1 --ckpt=ckpt/lunarlanding/a1-v1 --init --grad_norm_clip=0.1 --steps=3500 --save_interval=30

    from src.tasks import task_train_bm
    task_train_bm.build_parser(subparsers)
    # ./main train_bm --device=mps

    from src.tasks import task_testM
    task_testM.build_parser(subparsers)
    # ./main testM LunarLander-v3 a1 --ckpt=ckpt/lunarlanding/a1-v1/model_final.pth

    from src.tasks import task_landingH
    task_landingH.build_parser(subparsers)
    # ./main landingH


    # Parse arguments
    args = parser.parse_args()
    
    # Call the function associated with the chosen command
    args.func(args)